In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [2]:
df = pd.read_csv('gabor_with_glcm_features.csv')

list_1 = []
length = len(df['Text'])
array_2 = np.array(df['Text'])
for i in range(0, length):
    if array_2[i] < 2.3 :
        list_1.append(1)
    elif array_2[i] > 2.3 and array_2[i] < 3.6 :
        list_1.append(2)
    else:
        list_1.append(3)
        
df['state'] = list_1
df.drop(['Text','RadId'], axis = 1, inplace = True)
df.head()


lndbId  FindingId   contrast  dissimilarity    energy  homogeneity  \
0       1          1  14.565517       0.886692  0.606897     0.974756   
1       1          2  10.593103       0.940133  0.441379     0.981641   
2       1          1  10.593103       0.926015  0.441379     0.981641   
3       1          1  11.917241       0.940056  0.496552     0.979346   
4       2          1  10.593103       0.917460  0.441379     0.981641   

   correlation       ASM  Nodule  state  
0     0.866296  0.786223       1      3  
1     0.812525  0.883850       1      3  
2     0.852217  0.857503       1      3  
3     0.784559  0.883705       1      3  
4     0.868838  0.841733       1      3

In [3]:
Y = df['state']
Y

0       3
1       3
2       3
3       3
4       3
       ..
1377    3
1378    1
1379    1
1380    1
1381    1
Name: state, Length: 1382, dtype: int64

In [13]:
X = df.drop(['lndbId','FindingId','dissimilarity','energy','homogeneity','ASM','Nodule','state'], axis = 1)
#X = df.drop(['Text'], axis = 1)
#X = df[['contrast']['correlation']]
X.head()


contrast  correlation
0  14.565517     0.866296
1  10.593103     0.812525
2  10.593103     0.852217
3  11.917241     0.784559
4  10.593103     0.868838

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state = 42)
#X_train.corr()


In [18]:
X_train.drop(['ASM','dissimilarity','state'], axis = 1, inplace = True)
X_test.drop(['ASM','dissimilarity','state'], axis = 1, inplace = True)

C:\Users\Ishan\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [15]:
### KNN classifier

knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.8989169675090253
F1 score :  0.8722409840733869
Confusion matrix : 
 [[ 84   0   8]
 [  1   0  15]
 [  4   0 165]]


In [16]:
### SVM classifier

from sklearn import svm
clf = svm.SVC(kernel='poly')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.7509025270758123
F1 score :  0.7312284291296931
Confusion matrix : 
 [[ 86   0   6]
 [  4   0  12]
 [ 47   0 122]]


In [21]:
### logistic regression

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state = 12).fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)


Accuracy :  0.9133574007220217
F1 score :  0.8866922813309713
Confusion matrix : 
 [[ 84   0   8]
 [  0   0  16]
 [  0   0 169]]


C:\Users\Ishan\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [17]:
### decision tree

from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.8808664259927798
F1 score :  0.8607546471278786
Confusion matrix : 
 [[ 85   0   7]
 [  1   1  14]
 [ 10   1 158]]


In [1]:
# Plotting a Bar Graph to compare the features
plt.bar(X_train.columns, feature_importance_normalized) 
plt.xlabel('Feature Labels') 
plt.ylabel('Feature Importances') 
plt.title('Comparison of different Feature Importances') 
plt.show() 

NameError: name 'plt' is not defined