In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [3]:
df = pd.read_csv('gabor_lbp_features_1.csv')

list_1 = []
length = len(df['Text'])
array_2 = np.array(df['Text'])
for i in range(0, length):
    if array_2[i] < 2.3 :
        list_1.append(1)
    elif array_2[i] > 2.3 and array_2[i] < 3.6 :
        list_1.append(2)
    else:
        list_1.append(3)
df['state'] = list_1

#Normalizing the values
#df.drop(['Text','Volume','RadId'], axis = 1, inplace = True)
df['mean'] = df['mean']/ df['mean'].max()
df['std deviavtion'] = df['std deviavtion']/ df['std deviavtion'].max()
df['var'] = df['var']/ df['var'].max()
df.head()
df.corr()

lndbId     RadId  FindingId      mean  std deviavtion  \
lndbId          1.000000 -0.175611   0.273702  0.187661       -0.245208   
RadId          -0.175611  1.000000   0.071317  0.054504       -0.138679   
FindingId       0.273702  0.071317   1.000000  0.224009       -0.307148   
mean            0.187661  0.054504   0.224009  1.000000       -0.830802   
std deviavtion -0.245208 -0.138679  -0.307148 -0.830802        1.000000   
var            -0.184723 -0.085996  -0.230009 -0.926963        0.924418   
Nodule         -0.128921 -0.178026  -0.344867 -0.345593        0.644199   
Volume         -0.086666 -0.004452  -0.108236 -0.872933        0.537499   
Text           -0.130092 -0.131970  -0.308941 -0.289706        0.559518   
state          -0.094416 -0.140595  -0.293042 -0.265398        0.528322   

                     var    Nodule    Volume      Text     state  
lndbId         -0.184723 -0.128921 -0.086666 -0.130092 -0.094416  
RadId          -0.085996 -0.178026 -0.004452 -0.131970 -0.140595  
FindingId      -0.230009 -0.344867 -0.108236 -0.308941 -0.293042  
mean           -0.926963 -0.345593 -0.872933 -0.289706 -0.265398  
std deviavtion  0.924418  0.644199  0.537499  0.559518  0.528322  
var             1.000000  0.403718  0.722989  0.332653  0.305992  
Nodule          0.403718  1.000000  0.125990  0.937422  0.902804  
Volume          0.722989  0.125990  1.000000  0.110035  0.096892  
Text            0.332653  0.937422  0.110035  1.000000  0.982842  
state           0.305992  0.902804  0.096892  0.982842  1.000000

In [4]:
Y = df['state']
X = df.drop(['lndbId','FindingId', 'state','Volume','RadId','mean','var','Nodule','Text'], axis = 1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
X_train.head()

std deviavtion
826         0.067523
942         0.164937
1186        0.259473
1353        0.067523
811         0.067523

In [121]:
X_train.drop(['RadId','Text','std deviavtion'], axis = 1, inplace = True)
X_test.drop(['RadId','Text','std deviavtion'], axis = 1, inplace = True)
X_train.corr()

C:\Users\Ishan\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


mean       var    Nodule
mean    1.000000 -0.927844 -0.345901
var    -0.927844  1.000000  0.402101
Nodule -0.345901  0.402101  1.000000

In [6]:
### KNN classifier

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.9133574007220217
F1 score :  0.8948620685707993
Confusion matrix : 
 [[ 86   0   4]
 [  0   0  11]
 [  9   0 167]]


In [7]:
### SVM classifier

from sklearn import svm
clf = svm.SVC(kernel='poly')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.6353790613718412
F1 score :  0.49371618013882573
Confusion matrix : 
 [[  0   0  90]
 [  0   0  11]
 [  0   0 176]]


In [8]:
### logistic regression

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state = 12).fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f_score = f1_score(y_test, y_pred, average='weighted')
conf_mat = confusion_matrix(y_test, y_pred)
print('Accuracy : ', accuracy)
print('F1 score : ', f_score)
print('Confusion matrix : \n', conf_mat)

Accuracy :  0.8772563176895307
F1 score :  0.8600788435933264
Confusion matrix : 
 [[ 86   0   4]
 [  1   0  10]
 [ 19   0 157]]


In [ ]:
# Plotting a Bar Graph to compare the features
plt.bar(X_train.columns, feature_importance_normalized) 
plt.xlabel('Feature Labels') 
plt.ylabel('Feature Importances') 
plt.title('Comparison of different Feature Importances') 
plt.show() 